events {
    worker_connections 1024;
}

http {
    server_tokens off;

    upstream webhook {
        server saveinator:8000;
    }

    server {
        listen 8443 ssl;
        server_name saveinator-hooks.xdshka.party;

        ssl_certificate     /etc/letsencrypt/live/xdshka.party/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/xdshka.party/privkey.pem;

        location /webhook {
            proxy_pass http://webhook;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 120s;
        }

        location /health {
            proxy_pass http://webhook/health;
            proxy_set_header Host $host;
        }
    }
}
